# The URL of your website.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "/"

# Title of your site
title = "Arkayar"

# Your copyright notice - appears in site footer.
# To display a copyright symbol, type `&copy;`.
# copyright = "&copy; Rajesh Kasturirangan 2018"

theme = "one"

[params]
    navigation = ["archives.md", "about.md"]